# Generated by Django 3.1.1 on 2021-10-19 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_auto_20211019_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
    ]
