# Generated by Django 3.1.1 on 2021-10-19 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0006_auto_20211019_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='users',
            table='user',
        ),
    ]
