# Generated by Django 3.1.1 on 2021-10-24 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0008_users_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=256, null=True)),
                ('course_duration', models.CharField(blank=True, max_length=256, null=True)),
                ('course_fees', models.IntegerField()),
                ('course_status', models.CharField(choices=[('active', 'active'), ('deactive', 'deactive'), ('deleted', 'deleted')], default='active', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_access', models.BooleanField(default=False)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_app.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_access',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=256, null=True)),
                ('last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('course_fees', models.IntegerField()),
                ('course_status', models.CharField(choices=[('active', 'active'), ('deactive', 'deactive'), ('deleted', 'deleted')], default='active', max_length=20)),
                ('course_taken', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_app.course')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
